name: deploy

on:
  push:
    branches:
      - master

jobs:
  push-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: |
          pnpm install --no-frozen-lockfile
          pnpm run build
          touch .vitepress/dist/.nojekyll
          cp .vitepress/dist/index.html .vitepress/dist/404.html

      # - name: Delete gh-pages branch
      #   run: |
      #     git push origin --delete gh-pages

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          publish_branch: gh-pages
          publish_dir: .vitepress/dist
          cname: uilist.com
